import type { ImageSourcePropType } from 'react-native';

export const GAME_ICONS = {
  'class-warrior': require('../assets/sprites/icons/generated/class-warrior.png'),
  'class-scholar': require('../assets/sprites/icons/generated/class-scholar.png'),
  'class-monk': require('../assets/sprites/icons/generated/class-monk.png'),
  'class-ranger': require('../assets/sprites/icons/generated/class-ranger.png'),
  'stat-strength': require('../assets/sprites/icons/generated/stat-strength.png'),
  'stat-intelligence': require('../assets/sprites/icons/generated/stat-intelligence.png'),
  'stat-mindfulness': require('../assets/sprites/icons/generated/stat-mindfulness.png'),
  'stat-endurance': require('../assets/sprites/icons/generated/stat-endurance.png'),
  'stat-vitality': require('../assets/sprites/icons/generated/stat-vitality.png'),
  'progress-xp': require('../assets/sprites/icons/generated/progress-xp.png'),
  'resource-energy': require('../assets/sprites/icons/generated/resource-energy.png'),
  'resource-healing': require('../assets/sprites/icons/generated/resource-healing.png'),
  'quest-steps': require('../assets/sprites/icons/generated/quest-steps.png'),
  'quest-workout': require('../assets/sprites/icons/generated/quest-workout.png'),
  'quest-reading': require('../assets/sprites/icons/generated/quest-reading.png'),
  'quest-meditation': require('../assets/sprites/icons/generated/quest-meditation.png'),
  'quest-sleep': require('../assets/sprites/icons/generated/quest-sleep.png'),
  'quest-water': require('../assets/sprites/icons/generated/quest-water.png'),
  'quest-screen-free': require('../assets/sprites/icons/generated/quest-screen-free.png'),
  'quest-training': require('../assets/sprites/icons/generated/quest-training.png'),
  'quest-squat': require('../assets/sprites/icons/generated/quest-squat.png'),
  'quest-plank': require('../assets/sprites/icons/generated/quest-plank.png'),
  'quest-stairs': require('../assets/sprites/icons/generated/quest-stairs.png'),
  'quest-mobility': require('../assets/sprites/icons/generated/quest-mobility.png'),
  'quest-meal': require('../assets/sprites/icons/generated/quest-meal.png'),
  'quest-notes': require('../assets/sprites/icons/generated/quest-notes.png'),
  'quest-puzzle': require('../assets/sprites/icons/generated/quest-puzzle.png'),
  'quest-timer': require('../assets/sprites/icons/generated/quest-timer.png'),
  'quest-map': require('../assets/sprites/icons/generated/quest-map.png'),
  'quest-breath': require('../assets/sprites/icons/generated/quest-breath.png'),
  'quest-gratitude': require('../assets/sprites/icons/generated/quest-gratitude.png'),
  'quest-tea': require('../assets/sprites/icons/generated/quest-tea.png'),
  'quest-journal': require('../assets/sprites/icons/generated/quest-journal.png'),
  'quest-kindness': require('../assets/sprites/icons/generated/quest-kindness.png'),
  'quest-mountain': require('../assets/sprites/icons/generated/quest-mountain.png'),
  'quest-run': require('../assets/sprites/icons/generated/quest-run.png'),
  'quest-outdoors': require('../assets/sprites/icons/generated/quest-outdoors.png'),
  'quest-compass': require('../assets/sprites/icons/generated/quest-compass.png'),
  'quest-stretch': require('../assets/sprites/icons/generated/quest-stretch.png'),
  'quest-bike': require('../assets/sprites/icons/generated/quest-bike.png'),
  'quest-scout': require('../assets/sprites/icons/generated/quest-scout.png'),
  'quest-cards': require('../assets/sprites/icons/generated/quest-cards.png'),
  'quest-language': require('../assets/sprites/icons/generated/quest-language.png'),
  'quest-idea': require('../assets/sprites/icons/generated/quest-idea.png'),
  'combat-blades': require('../assets/sprites/icons/generated/combat-blades.png'),
  'combat-impact': require('../assets/sprites/icons/generated/combat-impact.png'),
  'combat-shield': require('../assets/sprites/icons/generated/combat-shield.png'),
  'combat-arcane': require('../assets/sprites/icons/generated/combat-arcane.png'),
  'combat-fist': require('../assets/sprites/icons/generated/combat-fist.png'),
  'combat-dragon': require('../assets/sprites/icons/generated/combat-dragon.png'),
  'combat-bow': require('../assets/sprites/icons/generated/combat-bow.png'),
  'combat-target': require('../assets/sprites/icons/generated/combat-target.png'),
  'combat-leaf': require('../assets/sprites/icons/generated/combat-leaf.png'),
  'combat-fire': require('../assets/sprites/icons/generated/combat-fire.png'),
  'combat-crown': require('../assets/sprites/icons/generated/combat-crown.png'),
  'combat-fortress': require('../assets/sprites/icons/generated/combat-fortress.png'),
  'combat-blood': require('../assets/sprites/icons/generated/combat-blood.png'),
  'combat-aegis': require('../assets/sprites/icons/generated/combat-aegis.png'),
  'combat-axe': require('../assets/sprites/icons/generated/combat-axe.png'),
  'combat-drum': require('../assets/sprites/icons/generated/combat-drum.png'),
  'skill-banner': require('../assets/sprites/icons/generated/skill-banner.png'),
  'skill-volcano': require('../assets/sprites/icons/generated/skill-volcano.png'),
  'skill-geometry': require('../assets/sprites/icons/generated/skill-geometry.png'),
  'skill-comet': require('../assets/sprites/icons/generated/skill-comet.png'),
  'skill-temple': require('../assets/sprites/icons/generated/skill-temple.png'),
  'skill-helix': require('../assets/sprites/icons/generated/skill-helix.png'),
  'skill-chain': require('../assets/sprites/icons/generated/skill-chain.png'),
  'skill-infinity': require('../assets/sprites/icons/generated/skill-infinity.png'),
  'skill-eye': require('../assets/sprites/icons/generated/skill-eye.png'),
  'skill-palm': require('../assets/sprites/icons/generated/skill-palm.png'),
  'skill-lungs': require('../assets/sprites/icons/generated/skill-lungs.png'),
  'skill-sunrise': require('../assets/sprites/icons/generated/skill-sunrise.png'),
  'skill-vortex': require('../assets/sprites/icons/generated/skill-vortex.png'),
  'status-trophy': require('../assets/sprites/icons/generated/status-trophy.png'),
  'skill-ghost': require('../assets/sprites/icons/generated/skill-ghost.png'),
  'skill-starfall': require('../assets/sprites/icons/generated/skill-starfall.png'),
  'dungeon-forge': require('../assets/sprites/icons/generated/dungeon-forge.png'),
  'dungeon-hatchling': require('../assets/sprites/icons/generated/dungeon-hatchling.png'),
  'dungeon-anvil': require('../assets/sprites/icons/generated/dungeon-anvil.png'),
  'dungeon-golem': require('../assets/sprites/icons/generated/dungeon-golem.png'),
  'dungeon-rose': require('../assets/sprites/icons/generated/dungeon-rose.png'),
  'dungeon-wolf': require('../assets/sprites/icons/generated/dungeon-wolf.png'),
  'dungeon-wave': require('../assets/sprites/icons/generated/dungeon-wave.png'),
  'dungeon-wing': require('../assets/sprites/icons/generated/dungeon-wing.png'),
  'dungeon-paw': require('../assets/sprites/icons/generated/dungeon-paw.png'),
  'dungeon-stars': require('../assets/sprites/icons/generated/dungeon-stars.png'),
  'dungeon-dagger': require('../assets/sprites/icons/generated/dungeon-dagger.png'),
  'dungeon-map': require('../assets/sprites/icons/generated/dungeon-map.png'),
  'status-lock': require('../assets/sprites/icons/generated/status-lock.png'),
  'status-warning': require('../assets/sprites/icons/generated/status-warning.png'),
  'status-victory': require('../assets/sprites/icons/generated/status-victory.png'),
  'status-defeat': require('../assets/sprites/icons/generated/status-defeat.png'),
} satisfies Record<string, ImageSourcePropType>;

export type GameIconName = keyof typeof GAME_ICONS;

const LEGACY_ICON_MAP: Record<string, GameIconName> = {
  '⚔️': 'class-warrior', '🧠': 'class-scholar', '🧘': 'class-monk', '🏹': 'class-ranger',
  '💪': 'stat-strength', '📚': 'stat-intelligence', '🪷': 'stat-mindfulness', '🏃': 'stat-endurance', '❤️': 'stat-vitality',
  '👟': 'quest-steps', '📖': 'quest-reading', '🌙': 'quest-sleep', '💧': 'quest-water', '📵': 'quest-screen-free',
  '🔥': 'combat-fire', '🛡️': 'combat-shield', '⚡': 'resource-energy', '💚': 'resource-healing', '🏆': 'status-trophy',
  '🗺️': 'dungeon-map', '🔒': 'status-lock', '⚠️': 'status-warning', '✅': 'status-victory', '❌': 'status-defeat',
  '🌋': 'skill-volcano', '☄️': 'skill-comet', '🏛️': 'skill-temple', '🧬': 'skill-helix', '🔗': 'skill-chain',
  '♾️': 'skill-infinity', '👁️': 'skill-eye', '🫁': 'skill-lungs', '🌅': 'skill-sunrise', '🌪️': 'skill-vortex',
  '👻': 'skill-ghost', '🌠': 'skill-starfall', '🥊': 'combat-fist', '🐉': 'combat-dragon', '🎯': 'combat-target',
  '🌿': 'combat-leaf', '👑': 'combat-crown', '🩸': 'combat-blood', '🪓': 'combat-axe', '🥁': 'combat-drum',
  '🧱': 'combat-fortress', '⚒️': 'dungeon-anvil', '🐺': 'dungeon-wolf', '🌊': 'dungeon-wave', '🪽': 'dungeon-wing',
  '🐾': 'dungeon-paw', '🌌': 'dungeon-stars', '🗡️': 'dungeon-dagger', '🌹': 'dungeon-rose', '⛰️': 'quest-mountain',
  '🚴': 'quest-bike', '🧭': 'quest-compass', '📝': 'quest-notes', '🧩': 'quest-puzzle', '⏱️': 'quest-timer',
  '🫖': 'quest-tea', '🙏': 'quest-gratitude', '📓': 'quest-journal', '🤝': 'quest-kindness', '🃏': 'quest-cards',
  '💡': 'quest-idea', '🌲': 'quest-outdoors', '🧘‍♂️': 'quest-meditation', '🏋️': 'quest-workout',
  '🏋️‍♂️': 'quest-workout', '🤸': 'quest-mobility', '🥗': 'quest-meal', '🪜': 'quest-stairs', '🧎': 'quest-stretch',
  '🫧': 'quest-breath', '🗣️': 'quest-language', '🛰️': 'quest-scout', '🏳️': 'skill-banner', '✊': 'combat-impact',
  '✋': 'skill-palm', '☯️': 'class-monk', '☯': 'class-monk', '✨': 'progress-xp', '⭐': 'progress-xp', '✦': 'progress-xp',
  '🔮': 'combat-arcane', '📐': 'skill-geometry', '🪨': 'dungeon-golem', '🐲': 'dungeon-hatchling', '⚙️': 'dungeon-forge',
  '🔤': 'quest-language', '⏳': 'quest-timer', '🌬️': 'quest-breath', '🍃': 'combat-leaf', '🍵': 'quest-tea',
  '🥾': 'quest-steps', '🦵': 'quest-squat', '🚲': 'quest-bike', '👀': 'skill-eye', '💥': 'combat-impact',
  '🏰': 'combat-fortress', '🔰': 'combat-aegis', '🚩': 'skill-banner', '🗿': 'dungeon-golem', '🔷': 'skill-geometry',
  '🧿': 'skill-eye', '🖐️': 'skill-palm', '🩷': 'resource-healing', '🌳': 'quest-outdoors', '🌀': 'skill-vortex',
  '🏔️': 'quest-mountain', '💫': 'skill-starfall', '🏺': 'skill-temple', '💨': 'resource-energy', '🦅': 'dungeon-wing',
  '🌧️': 'dungeon-wave', '🎒': 'quest-scout', '🌄': 'skill-sunrise', '🌃': 'dungeon-stars', '👊': 'combat-fist',
};

export function getGameIcon(token: string): ImageSourcePropType {
  return GAME_ICONS[token as GameIconName]
    ?? GAME_ICONS[LEGACY_ICON_MAP[token] ?? 'progress-xp'];
}
